// Comment intelligence: scrape a reel's comments, classify AI accusations /
// sentiment / "tells", and store a per-reel summary in Supabase.
import { db } from "./db";
import { scrapeComments } from "./rocksolid";

const AI = /\b(a\.?i\b|bot|fake|cgi|deepfake|ai[- ]?generated|generated by|not real|robot|render(ed)?|ai slop)\b/i;

const POS = /\b(beautiful|pretty|gorgeous|stunning|cute|wow|queen|goddess|perfect|amazing|love|hot|sexy|nice|angel|wife|marry|adorable|babe|🔥|😍|❤)\b/i;
const NEG = /\b(hate|trash|garbage|slop|disgust|stupid|cringe|banned?|pest|nonsense|annoying|worst|ugly|terrible|awful|gross|sick of|tired of|\bbs\b|shut up|just stop)\b/i;

// "why AI" tells
const TELLS: { key: string; re: RegExp }[] = [
  { key: "clipping / physics glitch", re: /\b(through (his|her|the)|arm|hand|finger|leg|clip|melt|morph|glitch|warp|shrank|shrink|passes? through|went through)\b/i },
  { key: "implausible / inconsistent height", re: /\b(height|too tall|7'?\s?\d|proportion|that tall|petite|ceiling|doorway|too big)\b/i },
  { key: "gaze / eye-line", re: /\b(look|eyes|gaze|star(e|ing)|glance|distract)\b/i },
  { key: "phone-raising trope", re: /\b(phone|filming|record|raise (their|her|the) phone|camera)\b/i },
  { key: "formula / repeated setup", re: /\b(same (guy|voice|man)|every video|every post|always the same|recycled)\b/i },
];

export type CommentSummary = {
  comments_analyzed: number;
  ai_count: number;
  ai_pct: number;
  pos_count: number;
  neg_count: number;
  tells: Record<string, number>;
  sample_ai: string[];
  sample_neg: string[];
};

export function analyzeComments(comments: string[]): CommentSummary {
  const uniq = Array.from(new Set(comments));
  const n = uniq.length || 1;
  let ai = 0,
    pos = 0,
    neg = 0;
  const tells: Record<string, number> = {};
  const sampleAi: string[] = [];
  const sampleNeg: string[] = [];

  for (const c of uniq) {
    const isAi = AI.test(c);
    if (isAi) {
      ai++;
      if (sampleAi.length < 8) sampleAi.push(c.slice(0, 160));
      for (const t of TELLS) if (t.re.test(c)) tells[t.key] = (tells[t.key] || 0) + 1;
    }
    if (POS.test(c)) pos++;
    if (NEG.test(c)) {
      neg++;
      if (sampleNeg.length < 8) sampleNeg.push(c.slice(0, 160));
    }
  }

  return {
    comments_analyzed: uniq.length,
    ai_count: ai,
    ai_pct: Math.round((ai / n) * 1000) / 10,
    pos_count: pos,
    neg_count: neg,
    tells,
    sample_ai: sampleAi,
    sample_neg: sampleNeg,
  };
}

// Scrape + analyze + upsert a single reel's comment insight.
export async function analyzeReel(reel: {
  shortcode: string;
  reel_url: string;
  account_handle: string;
  caption?: string;
  views?: number;
  comments?: number;
}, maxPages = 12) {
  const comments = await scrapeComments(reel.shortcode, maxPages);
  const s = analyzeComments(comments);
  await db()
    .from("comment_insights")
    .upsert(
      {
        account_handle: reel.account_handle,
        shortcode: reel.shortcode,
        reel_url: reel.reel_url,
        caption: reel.caption || null,
        views: reel.views || 0,
        comments_total: reel.comments || 0,
        comments_analyzed: s.comments_analyzed,
        ai_count: s.ai_count,
        ai_pct: s.ai_pct,
        pos_count: s.pos_count,
        neg_count: s.neg_count,
        tells: s.tells,
        sample_ai: s.sample_ai,
        sample_neg: s.sample_neg,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "reel_url" }
    );
  return s;
}

// Analyze comments for the reels of one account (or all). Heavy/slow.
export async function analyzeAccount(handle: string | null, opts: { reelLimit?: number; pages?: number; minComments?: number } = {}) {
  const reelLimit = opts.reelLimit ?? 60;
  const pages = opts.pages ?? 10;
  const minComments = opts.minComments ?? 1;

  let q = db()
    .from("our_reels")
    .select("shortcode, reel_url, account_handle, caption, views, comments")
    .gte("comments", minComments)
    .order("comments", { ascending: false })
    .limit(reelLimit);
  if (handle) q = q.ilike("account_handle", handle);
  const { data } = await q;

  let ok = 0;
  for (const r of data || []) {
    if (!r.shortcode) continue;
    try {
      await analyzeReel(r as any, pages);
      ok++;
    } catch {
      /* skip */
    }
  }
  return { reels: (data || []).length, analyzed: ok };
}
